apiVersion: v1
kind: ClusterRole
metadata:
  name: ingress-admin
rules:
  - resources:
    - ingresses 
    apiGroups:
    - extensions
    verbs:
    - create
    - get
    - list
    - watch
    - delete
    - update
