
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/kubernetes/ingress-nginx/images/grpc-fortune-teller*"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# Don't prune helper scripts from code-generator
[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
    name = "github.com/golang/glog"
    source = "k8s.io/klog/glog"

[[constraint]]
  name = "github.com/eapache/channels"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-proxyproto"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.7"

[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/ncabatoff/process-exporter"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/paultag/sniff"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/zakjan/cert-chain-resolver"
  version = "1.0.1"

[[constraint]]
  name = "gopkg.in/fsnotify/fsnotify.v1"
  version = "1.4.7"

[[constraint]]
  name = "gopkg.in/go-playground/pool.v3"
  version = "3.1.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "v1.13.3"

[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/apiserver"
  revision = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/cli-runtime"
  revision = "kubernetes-1.13.3"