apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: aws-pvc
   annotations:
      volume.beta.kubernetes.io/storage-class: aws-ebs
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest
  labels:
    name: web
    owner: Praparn_L
    version: "1.0"
    module: WebServer
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web
      owner: "Praparn_L"
      version: "1.0"
      module: WebServer
      environment: development
  template:
    metadata:
      labels:
        name: web
        owner: Praparn_L
        version: "1.0"
        module: WebServer
        environment: development
    spec:
      containers:
        - name: webtest
          image: labdocker/cluster:webservicelite_v1
          ports:
          - containerPort: 5000
            protocol: TCP
          volumeMounts:
          - name: aws-share-pvc
            mountPath: /usr/src/app
      initContainers:
        - name: downloadsource
          image: ubuntu:16.04
          command: ['/bin/bash', 'curl https://raw.githubusercontent.com/praparn/kubernetes_201904/master/WorkShop_2.7_Persistent_Storage/mainlite.py > /source/mainlite.py']
          volumeMounts:
          - name: aws-share-pvc
            mountPath: /source
      volumes:
      - name: aws-share-pvc
        persistentVolumeClaim:
          claimName: aws-pvc