{{ if not .Values.controller.defaultTLS.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: default-server-secret
  labels:
    app: {{ .Values.controller.name | trunc 63 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  tls.crt: {{ .Values.controller.defaultTLS.cert }}
  tls.key: {{ .Values.controller.defaultTLS.key }}
{{- end }}
